apiVersion: v1
kind: Service
metadata:
  name: great-thanos-service
spec:
  selector:
    app: great-thanos-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007  # Optional: specify a port or let Kubernetes choose
  type: NodePort
